- name:  Download Scala
  command: wget http://www.scala-lang.org/files/archive/scala-{{scala_version}}.tgz chdir=/tmp creates=/tmp/scala-{{ scala_version }}.tgz

- name: Make sure the scala directory is present
  action: file path="/usr/local/java/" state=directory

- name:  Unpack the compressed Scala binaries
  command: tar -xvzf /tmp/scala-{{ scala_version }}.tgz chdir=/usr/local/java creates=/usr/local/java/scala-{{ scala_version }}

- name:  Set the permissions on the Scala binaries
  file: path=/usr/local/java/scala-{{ scala_version }}/bin state=directory mode=0755 recurse=yes

- name:  Update the symbolic link to the Scala install
  file: path=/usr/local/java/scala src=/usr/local/java/scala-{{ scala_version }} state=link force=yes

#- name:  Add the Scala binary to the system path (/etc/profile)
#  lineinfile: "dest=/etc/profile regexp='^SCALA_HOME=/usr/local/java/scala' line='SCALA_HOME=/usr/local/java/scala' state=present"
#  lineinfile: "dest=/etc/profile regexp='^PATH=.*SCALA_HOME.*' line='PATH=$PATH:$SCALA_HOME/bin' state=present"

#- name:  Inform the system where Scala is located
#  command: "{{ item }}"
#  with_items:
#    - update-alternatives --install "/usr/bin/scala" "scala" "/usr/local/java/scala/bin/scala" 1
#    - update-alternatives --install "/usr/bin/scalac" "scalac" "/usr/local/java/scala/bin/scalac" 1
#    - update-alternatives --install "/usr/bin/scalap" "scalap" "/usr/local/java/scala/bin/scalap" 1

#- name:  Set the system default for Scala
#  command: "{{ item }}"
#  with_items:
#   - update-alternatives --set scala /usr/local/java/scala/bin/scala
#    - update-alternatives --set scalac /usr/local/java/scala/bin/scalac
#    - update-alternatives --set scalap /usr/local/java/scala/bin/scalap
