- name: Remove Mesos master conf, if available on slaves
  file: state=absent path=/etc/init/mesos-master.conf

- name: Adding Mesos-Slave Config
  file: state=directory path=/etc/mesos-slave/

- name: Adding Mesos-Slave working directory
  file: state=directory path={{ mesos_slaves_work_dir }} owner=eran

- name: Adding containerizers to mesos-slave
  template: src=containerizers.j2 dest=/etc/mesos-slave/containerizers

- name: Adding docker clean up timeout to mesos-slave
  template: src=docker_remove_delay.j2 dest=/etc/mesos-slave/docker_remove_delay

- name: Changing working directory for slaves
  template: src=work_dir.j2 dest=/etc/mesos-slave/work_dir

- name: Increase the executor timeout to account for the potential delay in pulling a docker image to the slave
  template: src=executor_registration_timeout.j2 dest=/etc/mesos-slave/executor_registration_timeout

- name: Creating Mesos Slave config file
  template: src=conf-mesos-slave.j2 dest=/etc/default/mesos-slave

- name: Creating Mesos slave script
  template: src=init-mesos-slave.j2 dest=/etc/init/mesos-slave.conf
  notify:
    - Restart mesos-slave

- name: Restarting mesos-slave
  service: name=mesos-slave state=restarted


