---
- name: Add apt-key
  apt_key: id=E56151BF keyserver=keyserver.ubuntu.com state=present

- name: Add mesosphere repo
  apt_repository: repo='deb http://repos.mesosphere.io/{{ansible_distribution|lower}} {{ansible_distribution_release|lower}} main' state=present

- name: Install Debian OS packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - unzip
    - python-setuptools
    - python-dev
    - apt-transport-https
    - mesos={{marathon_mesos_version}}-1.0.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}
    - marathon={{marathon_major_version}}-{{marathon_minor_version}}.{{ansible_distribution|lower}}{{ansible_distribution_version.split('.')|join('')}}

- name: Copying marathon config file
  template: src=marathon.j2 dest=/etc/init/marathon.conf
  notify: restart marathon