- name: Check install location
  file: path={{marathon_install_location}} state=directory

- name: Download Marathon version {{ marathon_major_version }}
  get_url: url={{marathon_url}} dest={{marathon_dest_file}}

- name: Extract Archive
  command:  tar -xzf {{ marathon_dest_file }} --strip 1 -C {{ marathon_install_location }}
  sudo: yes